# Generated by Django 3.0.8 on 2021-04-13 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_tabla', models.CharField(max_length=60)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('tipo_accion', models.CharField(blank=True, max_length=50, null=True)),
                ('Dato_anterior', models.CharField(blank=True, max_length=400)),
                ('Dato_despues', models.CharField(blank=True, max_length=400)),
                ('campo_afectado', models.CharField(blank=True, max_length=50)),
                ('ip_accion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='historial_contrasenia',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contrasenia', models.CharField(blank=True, max_length=128, null=True)),
                ('ip_accion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['fecha'],
            },
        ),
    ]
