# Generated by Django 3.0.8 on 2021-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial_contrasenia',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Historial Contraseñas'},
        ),
        migrations.AddField(
            model_name='log',
            name='nombre_equipo',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
