# Generated by Django 3.0.8 on 2021-04-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0002_auto_20210413_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='nombre_equipo',
            new_name='user_log',
        ),
    ]
