# Generated by Django 3.1.7 on 2021-04-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'departamentos',
                'ordering': ['id_departamento'],
            },
        ),
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=120, unique=True, verbose_name='Nombre de la empresa')),
                ('descripcion', models.CharField(blank=True, max_length=450, verbose_name='Descripción')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('nombre_contacto', models.CharField(blank=True, max_length=80, verbose_name='Nombre del contacto')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'empresas',
                'ordering': ['id_empresa'],
            },
        ),
        migrations.CreateModel(
            name='puestos',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RRHH.departamentos')),
            ],
            options={
                'verbose_name_plural': 'puestos',
                'ordering': ['id_puesto'],
            },
        ),
    ]
