# Generated by Django 3.0.8 on 2021-04-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='id_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='RRHH.empresas'),
        ),
    ]
