# Generated by Django 3.0.8 on 2021-04-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_departamentos_id_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RRHH.empresas'),
        ),
    ]
