# Generated by Django 3.0.8 on 2021-04-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contabilizador_visitas',
            fields=[
                ('id_visita_web', models.AutoField(primary_key=True, serialize=False)),
                ('fch_visita_web', models.DateTimeField(auto_now_add=True)),
                ('ip_visita_web', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
