# Generated by Django 3.0.8 on 2021-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabilizador_visitas',
            name='ip_visita_web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
