# Generated by Django 3.1.7 on 2021-04-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pantallas',
            fields=[
                ('id_pantalla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Pantalla')),
            ],
            options={
                'verbose_name_plural': 'pantallas',
                'ordering': ['id_pantalla'],
            },
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('tiene_permisos', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'roles',
                'ordering': ['id_rol'],
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Correo Electrónico')),
                ('nombres', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellidos')),
                ('id_departamento', models.IntegerField(blank=True, null=True, verbose_name='Departamento')),
                ('id_puesto', models.IntegerField(blank=True, null=True, verbose_name='Puesto')),
                ('ip_ultimo_acceso', models.CharField(blank=True, max_length=50)),
                ('fch_ultimo_login', models.CharField(blank=True, max_length=70)),
                ('fch_ultimo_cambio_contrasenia', models.CharField(blank=True, max_length=70)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('fch_modificacion', models.DateTimeField(null=True)),
                ('fch_cambio_password', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('primer_ingreso', models.IntegerField(blank=True, default=1, null=True)),
                ('cambiar_contrasenia', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='1', max_length=1)),
                ('bloqueado', models.CharField(choices=[('1', 'Bloqueado'), ('0', 'Desbloqueado')], default='0', max_length=1)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('id_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Usuario.roles', verbose_name='Perfil de Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('ver', models.IntegerField(blank=True, default=1, null=True)),
                ('actualizar', models.IntegerField(blank=True, default=1, null=True)),
                ('crear', models.IntegerField(blank=True, default=1, null=True)),
                ('borrar', models.IntegerField(blank=True, default=1, null=True)),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('borrado', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=1)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuario.roles', verbose_name='Perfil de Usuario')),
                ('pantalla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuario.pantallas', verbose_name='Pantalla')),
            ],
            options={
                'verbose_name_plural': 'permisos',
                'ordering': ['id_permiso'],
            },
        ),
    ]
