# Generated by Django 3.0.8 on 2021-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
