# Generated by Django 3.0.8 on 2021-04-13 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_usuario_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='politicas_contrasenia',
            fields=[
                ('id_politica', models.AutoField(primary_key=True, serialize=False)),
                ('dias_expiracion_contrasenia', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(360)], verbose_name='Días de Expiración')),
                ('longitud_minima_contrasenia', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(25)], verbose_name='Longitud Mínima')),
                ('longitud_maxima_contrasenia', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50)], verbose_name='Longitud Máxima')),
                ('complejidad_contrasenia', models.CharField(choices=[('1', 'Incluir letras mayúsculas y minúsculas, números y caracteres especiales'), ('2', 'Incluir letras mayúsculas y minúsculas, números'), ('3', 'Incluir letras minúsculas, números'), ('4', 'Sin Restricciones')], default='4', max_length=1, verbose_name='Complejidad de Contraseña')),
                ('intentos_sesion_maximo', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)], verbose_name='Intentos Máximos de Inicio de Sesión')),
                ('fch_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fch_modificacion', models.CharField(blank=True, max_length=35)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
