# Generated by Django 3.0.8 on 2021-04-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20210414_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fch_ingreso_labores',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso a Laborar'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/%Y/%m/%d', verbose_name='Imagen de Perfil'),
        ),
    ]
