# Generated by Django 3.0.8 on 2021-04-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20210416_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fch_ingreso_labores',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso a Laborar'),
        ),
    ]
