# Generated by Django 3.0.8 on 2021-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_auto_20210420_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fch_cambio_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fch_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
