# Generated by Django 3.0.8 on 2021-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_auto_20210421_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantallas',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombres'),
        ),
    ]
